name: Swimbols

configs:
  Release: release

options:
  minimumXcodeGenVersion: 2.30.0
  xcodeVersion: 13.0
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: 11.0
    iOS: 15.0
  bundleIdPrefix: com.imthath.swimbols

attributes:
  ORGANIZATIONNAME: Vaan Corporation

packages:
  SFSafeSymbols:
    url: https://github.com/SFSafeSymbols/SFSafeSymbols
    from: 4.1.0
  CanvasKit:
#    path: ../../Frameworks/CanvasKit
    url: https://github.com/skydevz/canvas-kit
    from: 0.1.1
  MIDataStore:
    url: https://github.com/imthath-m/mi-data-store
    from: 0.1.0
  Purchases:
    url: https://github.com/RevenueCat/purchases-ios
    from: 4.17.2

targets:
  Swimbols-macOS:
    type: application
    platform: macOS
    sources:
     - path: Shared
     - path: macOS
    configFiles:
      Release: Configs/Release.xcconfig
    postCompileScripts:
      - name: SwiftLint
        script: ./lint.sh
        basedOnDependencyAnalysis: false
    dependencies:
      - package: SFSafeSymbols
      - package: CanvasKit
      - package: MIDataStore
      - package: Purchases
        product: RevenueCat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)
        PRODUCT_NAME: $(APP_NAME)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: macOS/Info.plist
      Release:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Distribution"

  Swimbols-iOS:
    type: application
    platform: iOS
    sources: 
      - path: Shared
      - path: iOS
    configFiles:
      Release: Configs/Release.xcconfig
    postCompileScripts:
      - name: SwiftLint
        script: ./lint.sh
    dependencies:
      - package: SFSafeSymbols
      - package: CanvasKit
      - package: MIDataStore
      - package: Purchases
        product: RevenueCat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX)
        PRODUCT_NAME: $(APP_NAME)
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        INFOPLIST_FILE: iOS/Info.plist
      Release:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Distribution"
